python -m torch.distributed.run --nproc_per_node 2 --master_port 10000 train.py --gpu 0,1 --dataset regdb --text_mode v2 --trial 1 --log_path tmp
python -m torch.distributed.run --nproc_per_node 2 --master_port 10000 train.py --gpu 0,1 --dataset regdb --text_mode v2 --trial 2 --log_path tmp
python -m torch.distributed.run --nproc_per_node 2 --master_port 10000 train.py --gpu 0,1 --dataset regdb --text_mode v2 --trial 3 --log_path tmp
python -m torch.distributed.run --nproc_per_node 2 --master_port 10000 train.py --gpu 0,1 --dataset regdb --text_mode v2 --trial 4 --log_path tmp
python -m torch.distributed.run --nproc_per_node 2 --master_port 10000 train.py --gpu 0,1 --dataset regdb --text_mode v2 --trial 5 --log_path tmp
python -m torch.distributed.run --nproc_per_node 2 --master_port 10000 train.py --gpu 0,1 --dataset regdb --text_mode v2 --trial 6 --log_path tmp
python -m torch.distributed.run --nproc_per_node 2 --master_port 10000 train.py --gpu 0,1 --dataset regdb --text_mode v2 --trial 7 --log_path tmp
python -m torch.distributed.run --nproc_per_node 2 --master_port 10000 train.py --gpu 0,1 --dataset regdb --text_mode v2 --trial 8 --log_path tmp
python -m torch.distributed.run --nproc_per_node 2 --master_port 10000 train.py --gpu 0,1 --dataset regdb --text_mode v2 --trial 9 --log_path tmp
python -m torch.distributed.run --nproc_per_node 2 --master_port 10000 train.py --gpu 0,1 --dataset regdb --text_mode v2 --trial 10 --log_path tmp
